### ISSUE TITLE
[C4GT] Ability to book an appointment via Whatzapp

### ISSUE THREAD

**Issue by gsluthra** [Bahmni/openmrs-module-bahmniapps#572]
_Note: Bahmni team tracks all issues in [public JIRA repository](https://bahmni.atlassian.net/wiki/spaces/BAH/pages/116069555/Contributing+to+Bahmni#ContributingtoBahmni-4.ContributeasaDeveloper%2FCoder%2FAnalyst%2FQAtoBahmni). But since Code4GovTech requires all project details to be created in Github, we are writing the project details here. But eventually as per Bahmni community process, the actual stories will tracked in JIRA, and issue number in commit messages will need to be of JIRA ticket number (and optionally Github issue number)._ 

### Purpose
Allow patients to book an appointment in Bahmni via whatzapp.

### Introducing Bahmni
1. Bahmni is an opensource hospital management system, used in low resource environments and is currently live in 600+ facilities across the world, including India, Nepal, Bangladesh, Uganda, Lesotho, Kenya, Cambodia, etc. It is also recognized as a Digital Public Good (DPG) by DPGA and Digital Square Alliance. For more details on Bahmni please visit: https://bahmni.org
2. One can try out Bahmni online using our demo servers here: [Online Bahmni Demo](https://bahmni.atlassian.net/wiki/spaces/BAH/pages/61997323/Bahmni+Online+Demo)

### Feature details
1. Bahmni has an Appointment Module, to book an appointment for a patient. See documentation here: [Create Appointments](https://bahmni.atlassian.net/wiki/spaces/BAH/pages/138182707/Creating+and+Managing+Appointments)
2. The above screen is used by Registration Desk to book an appointment for a patient. 
3. We would like the ability for patients to use Whatzapp for performing an appointment booking. For starters, we can support this feature only for already registered patients in the system (so that we don't have to implement Patient Registration via Whatzapp). 
4. This feature will require the contributor to explore how Whatzapp can be used to speak to Bahmni over REST/FHIR APIs. 

### Learning Path
1. Complexity: Medium.
2. Skills Required: Frontend (Whatzapp API/Programming). Backend (Java, MySQL). Local Install (Docker). 
3. Name of Mentors: @gsluthra @angshu 
4.  Project Size: 4-6 weeks

### Product Setup
1. Docker based local setup. See: [Running Bahmni on Docker](https://bahmni.atlassian.net/wiki/spaces/BAH/pages/299630726/Running+Bahmni+on+Docker)

### Acceptance Criteria

- [ ] 1. An existing patient should be able to see available appointment slots in a Clinic for a Service via Whatzapp.
- [ ] 2. Patient should be able to book an appointment via Whatzapp and receive confirmation of booking.
- [ ] 3. The Bahmni UI should show the above booked slot as not-available, and show all details of patient (as it does now). And it should also indicate that this booking was done via Whatzapp. 
- [ ] 4. Pull Request reviewed/merged into Bahmni codebase, after feedback from Bahmni core team & mentor has been incorporated.
- [ ] 5. Automation Tests pass on Github Actions CI.
- [ ] 6. New Feature is deployed on our DEV environment.
- [ ] 7. There is configuration which enables/disables this feature (so a Clinic can choose if they want to support this feature or not). 
- [ ] 8. All message strings are added into translation files. 
- [ ] 9. A showcase is done of this feature in our public Bahmni PAT call (every Wed evening at 6:30 pm IST). 

### Milestones
- [ ] 1. Install Bahmni locally. 
- [ ] 2. Demo the appointment functionality, to ensure the contributor has understood the functionality.
- [ ] 3. Work with mentor to create low-fi design/mockup for how the communication will flow in Whatzapp.
- [ ] 4. Create stories in JIRA (possibly 4-5) which list all requirements to develop this feature.
- [ ] 5. Complete the development (with unit tests), with local showcase from your own machine.
- [ ] 6. Raise PR for each story, and have it reviewed.
- [ ] 7. Merge PRs for all stories.
- [ ] 8. Validate and showcase the feature from our DEV server.
- [ ] 9. Document the new feature in Bahmni public WIKI.
- [ ] 10. Showcase the new feature in Community PAT call over zoom.

### C4GT
This issue is nominated for Code for GovTech (C4GT) 2023 edition. C4GT is India's first annual coding program to create a community that can build and contribute to global [Digital Public Goods](https://www.codeforgovtech.in/digitalpublicgoods). If you want to use Open Source GovTech to create impact, then this is the opportunity for you! More about C4GT here: https://codeforgovtech.in/

**Comment by pvcodes** [comment]
Hey @gsluthra, I'm assuming whatzapp is a typo, you are referring to WhatsApp?

**Comment by gsluthra** [comment]
### Want to explore Bahmni? 

Please install Bahmni and join our Slack (#community) channel. You can pick a volunteer ticket to get familiar. Thanks!

Links: 
1. Docker: https://bahmni.atlassian.net/wiki/spaces/BAH/pages/3117744129/Getting+Started+Quickly+with+Bahmni+on+Docker
2. Slack/Bahmni Talk Forum: https://bahmni.atlassian.net/wiki/spaces/BAH/pages/414646273/Communication+Channels+and+Tools+Discourse+Slack
3. Volunteer JIRA Links: https://bahmni.atlassian.net/wiki/spaces/BAH/pages/116069555/Contributing+to+Bahmni#ContributingtoBahmni-4.ContributeasaDeveloper%2FCoder%2FAnalyst%2FQAtoBahmni
4. You will need to open a free Atlassian account to self-sign-up on Bahmni JIRA.

**Comment by gsluthra** [comment]
> Hey @gsluthra, I'm assuming whatzapp is a typo, you are referring to WhatsApp?

Yes. Fixed the typo. Thanks for pointing out : )

**Comment by SigireddyBalasai** [comment]
I love this

**Comment by siddhesh-desai** [comment]
Hello @gsluthra and @angshu! I am Siddhesh Desai. I was impressed by the objectives of Bahmni, and would like to build this feature and be the part of the community as it aligns with my interests and skills. I will be sending my proposal soon.

**Comment by KavyaSethia** [comment]
Hello, @gsluthra and @angshu I am Kavya Sethia. Being proficient in Java and making a bot, I would like to contribute to this project and create a bot for the Bahmni. Looking forward to connecting with you and discussing this further.

**Comment by Darshan2003** [comment]
Hey @gsluthra and @angshu, I am interested in contributing to this project. Any discord or slack server that I should join?

**Comment by hetkumark** [comment]
Hello Mentors, can you please describe what all I may contribute towards this project?

**Comment by Aniket28dot** [comment]
Hii @gsluthra and @angshu I have just built this appointment booking system from scratch using Whatsapp business apis a month ago. Also handled several edge cases while developing it (involving schedule and holidays of doctors). I came to know about C4GT just a few days back and was exploring the projects, and I came across Bahmni. Think, I could be of help here.

**Comment by vabs212** [comment]
hi @gsluthra @angshu  i have worked on this type of module but on .net technology. i would like to be a part of this project. i will  e sending my proposal soon. hope to be working with you

**Comment by angshu** [comment]
@Aniket28dot @vabs212 thanks for your interest in this issue. As you would know, this is meant for Code4GovTech initiative. Hence any proposal must follow the the Code4GovTech process and in appropriate channels. You are most welcome to work with Bahmni community as volunteer, irrespective of a proposal acceptance. 
Note, we would like to build in java, as majority of the Bahmni backend compoents are in java, and you can potentially reuse existing libraries, code, patterns etc.
